version: 0.2

env:
  variables:
    DOCKER_COMPOSE_URL: "https://raw.githubusercontent.com/evershopcommerce/evershop/main/docker-compose.yml"

phases:
  install:
    commands:
      - echo "Installing docker & docker compose plugin"
      - yum update -y
      - amazon-linux-extras install docker -y
      - service docker start
      - usermod -a -G docker ec2-user

  pre_build:
    commands:
      - echo "Downloading docker-compose.yml"
      - curl -sSL $DOCKER_COMPOSE_URL -o docker-compose.yml

  build:
    commands:
      - echo "Running docker compose"
      - docker compose up -d